openapi: 3.0.0
info:
  title: Sample Register API
  version: 1.0.0
paths:
  /register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Registration successful
        '400':
          description: Invalid input
